[phases.setup]
nixPkgs = ["git", "python311", "python311Packages.pip", "ffmpeg"]

[phases.install]
cmds = [
  "npm install --legacy-peer-deps",
  "pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "node app.js"
